[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
